### ISSUE TITLE
Assistent zum Konfigurieren

### ISSUE THREAD

**Issue by DwarfLop** [Terax235/discord-bumpbot#1]
(Wenn du Lust hast :D)

Für Leute, die wenig von der Materie Node.js verstehen, könnte man einen Assistent bauen, mit dem die Bumpbots in Discord hinzugefügt werden können.

Zum Beispiel:

Nenne mir die ID des Bots
(ID wird geschrieben)
Bot prüft, ob der Bot auf dem Server ist und online ist

Gebe den Command ein, den der Bot zum Bumpen verwendet.

Gebe den Intervall wie folgt an:

HH.MM.SS

(Überprüfen, ob das Format richtig ist)

Nutzt der Bot eine Webseite? 
Ja/Nein angeben

Wenn ja, Frage nach der Webseite, Überprüfung der URL,
wenn nein, fortfahren.

Der Bot wurde hinzugefügt.
Du kannst weitere Bots mit `Command` hinzufügen.

Abspeichern in die JSON-Datei.

**Comment by Terax235** [comment]
Habs gelesen, werde mich drum kümmern.

**Comment by Terax235** [comment]
Ich werde das so machen, dass man über eine Webseite (wird in der Readme stehen) ein Objekt generieren kann und dieses dann per Befehl in der config speichern kann.

**Comment by Terax235** [comment]
Erledigt.

**Comment by DwarfLop** [comment]
:3
